AUTHORIZED_USERS:
- pedrodombrowski
- sauloecker
CONTENT_TYPES:
- clip
- video
- highlight
LOG_FILE_PATH: command_log.csv
MAX_VIDEO_TIME: '30'
OBS_HOST: localhost
OBS_PASSWORD: pBh6O8M3sq7vmZbE
OBS_PORT: 4455
TWITCH_CLIENT_ID: km8d199im6uwb25bojrkeql2nigjl1
TWITCH_CLIENT_SECRET: bu8xo9cfmxrmxbrb4nhnb0afte676h
TWITCH_USERNAME: pedrodombrowski
BLOCKED_PERIOD: 08-12
