AUTHORIZED_USERS:
- some_user_name
CONTENT_TYPES:
- clip
- video
- highlight
LOG_FILE_PATH: command_log.csv
MAX_VIDEO_TIME: '30'
OBS_HOST: localhost
OBS_PASSWORD: obs_websocket_password
OBS_PORT: 4455
TWITCH_CLIENT_ID: your_client_id
TWITCH_CLIENT_SECRET: your_client_secret
TWITCH_REDIRECT_URI: http://localhost:5000/auth/callback
TWITCH_USERNAME: your_username
BLOCKED_PERIOD: 08-23