TWITCH_CLIENT_ID: your_client_id
TWITCH_CLIENT_SECRET: your_client_secret
OBS_HOST: localhost
OBS_PORT: 4455
OBS_PASSWORD: obs_websocket_password
TWITCH_OAUTH_TOKEN: your_oath_token
TWITCH_USERNAME: your_username
AUTHORIZED_USERS:
- some_user_name
MAX_VIDEO_TIME: '30'
TWITCH_REDIRECT_URI: http://localhost:5000/auth/callback